/* Generated By:JavaCC: Do not edit this line. CompilateurFonctionConstants.java */
package fr.orsys.grapheur.graphe.grammaire;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CompilateurFonctionConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int OPERATEUR_ADDITION = 6;
  /** RegularExpression Id. */
  int OPERATEUR_SOUSTRACTION = 7;
  /** RegularExpression Id. */
  int OPERATEUR_DIVISION = 8;
  /** RegularExpression Id. */
  int OPERATEUR_MULTIPLICATION = 9;
  /** RegularExpression Id. */
  int VARIABLE = 10;
  /** RegularExpression Id. */
  int CONSTANTE_E = 11;
  /** RegularExpression Id. */
  int CONSTANTE_PI = 12;
  /** RegularExpression Id. */
  int NOM_FONCTION = 13;
  /** RegularExpression Id. */
  int SEPARATEUR_DECIMAL = 14;
  /** RegularExpression Id. */
  int NOMBRE = 15;
  /** RegularExpression Id. */
  int PARENTHESE_GAUCHE = 16;
  /** RegularExpression Id. */
  int PARENTHESE_DROITE = 17;
  /** RegularExpression Id. */
  int SEPARATEUR_PARAMETRES = 18;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"+\"",
    "\"-\"",
    "\"/\"",
    "\"*\"",
    "<VARIABLE>",
    "\"e\"",
    "\"pi\"",
    "<NOM_FONCTION>",
    "\".\"",
    "<NOMBRE>",
    "\"(\"",
    "\")\"",
    "\",\"",
  };

}
